#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Apr  4 19:35:00 2019

@author: mohit
"""

from pyfirmata import Arduino, util
import time

board = Arduino("/dev/tty.usbmodem14101")

iterator = util.Iterator(board)
iterator.start()

motor = board.get_pin('d:3:p')

motor.write(0.8)

time.sleep(20.0)

board.exit()